apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app.kubernetes.io/component: public-api
    app.kubernetes.io/name: httpbin
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: public-api
    app.kubernetes.io/name: httpbin
