apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  labels:
    app.kubernetes.io/component: public-api
    app.kubernetes.io/name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: public-api
      app.kubernetes.io/name: httpbin
  template:
    metadata:
      labels:
        app.kubernetes.io/component: public-api
        app.kubernetes.io/name: httpbin
    spec:
      volumes:
        - name: blablafiles
          configMap:
            name: blablafiles
      containers:
        - name: httpbin
          image: "kennethreitz/httpbin:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/dontcare
              name: blablafiles
              subPath: README.md
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 200M
            requests:
              cpu: 10m
              memory: 50M
